{--
Copyright (c) 2014 Gorka Suárez García

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
--}

{- ***************************************************************

    The sequence of triangle numbers is generated by adding the
    natural numbers. So the 7th triangle number would be
    1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would
    be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1,3
    6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

    We can see that 28 is the first triangle number to have over
    five divisors.

    What is the value of the first triangle number to have over
    five hundred divisors?

*************************************************************** -}
module Problem0012 (main) where

multipleOf :: (Integral a) => a -> a -> Bool
multipleOf a b = (mod a b) == 0

getDivisors :: (Integral a) => a -> [a]
getDivisors n = [x | x <- [1..n], multipleOf n x]

findTriangleValue :: Int -> Integer
findTriangleValue bottom = ftv 2 1
    where ftv n v = if bottom < len then v
                    else ftv (n + 1) (v + n)
              where len = length $ getDivisors v

main = do putStr "The value of the first triangle number to have "
          putStrLn $ "over 500 divisors is " ++ show result ++ "."
    where result = findTriangleValue 500